services:
  # to run in dev mode - $docker compose up cbs-dev
  cbs-dev:
    build:
      context: .
      target: dev-stage
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  # to run in prod mode - $docker compose up cbs-prod
  cbs-prod:
    build:
      context: .
      target: production-stage
    ports:
      - "8081:80" # Use a different port to avoid conflicts
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g "daemon off;"